# Generated by Django 3.2.9 on 2022-03-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_replie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replie',
            name='image',
        ),
    ]
