# Generated by Django 3.2.9 on 2022-05-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='review',
            field=models.CharField(max_length=255),
        ),
    ]
